# Generated by Django 3.1.5 on 2021-01-22 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=50)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
